services:
  telegraf:
    image: telegraf:1.33.0
    volumes:
      - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - cms-network
      - opensearch-network
    restart: always

  fluent-bit:
    image: fluent/fluent-bit:3.2.3
    user: root
    volumes:
      - ./conf/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - cms-network
      - opensearch-network
    ports:
      - "24224:24224"
    command: ["fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: always

  opensearch:
    image: opensearchproject/opensearch:2.18.0
    environment:
      - node.name=opensearch
      - discovery.type=single-node
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536  # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - data_opensearch:/usr/share/opensearch/data
      #- ./conf/opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml:ro
    ports:
      - 9200:9200
      - 9600:9600  # required for Performance Analyzer
    networks:
      - opensearch-network
    restart: always

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.18.0
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    ports:
      - 5601:5601
    #volumes:
    #  - ./conf/opensearch-dashboards/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml:ro
    networks:
      - opensearch-network
    restart: always

  data-prepper:
    image: opensearchproject/data-prepper:2.10.2
    volumes:
      - ./conf/data-prepper/pipelines.yaml://usr/share/data-prepper/pipelines/pipelines.yaml:ro
    networks:
      - opensearch-network
    ports:
      - 5044:5044
    mem_limit: ${MEM_LIMIT}
    restart: always
